### ISSUE TITLE
Build error error: pathspec '^1.0.0' did not match any file(s) known to git.

### ISSUE THREAD

**Issue by NicoHood** [Zenithar/hugo-theme-bleak#48]
```
628 silly pacote range manifest for repeat-string@^1.5.2 fetched in 31ms
629 http fetch GET 304 https://registry.npmjs.org/is-utf8 25ms (from cache)
630 silly pacote range manifest for is-utf8@^0.2.0 fetched in 26ms
631 http fetch GET 304 https://registry.npmjs.org/is-buffer 18ms (from cache)
632 silly pacote range manifest for is-buffer@^1.1.5 fetched in 19ms
633 http fetch GET 304 https://registry.npmjs.org/is-arrayish 21ms (from cache)
634 silly pacote range manifest for is-arrayish@^0.2.1 fetched in 22ms
635 silly fetchPackageMetaData error for @bower_components/ev-emitter@github:metafizzy/ev-emitter#^1.0.0 Command failed: /usr/bin/git checkout ^1.0.0
635 silly fetchPackageMetaData error: pathspec '^1.0.0' did not match any file(s) known to git.
636 silly fetchPackageMetaData error for @bower_components/desandro-matches-selector@github:desandro/matches-selector#^2.0.0 Command failed: /usr/bin/git checkout ^2.0.0
636 silly fetchPackageMetaData error: pathspec '^2.0.0' did not match any file(s) known to git.
637 silly fetchPackageMetaData error for @bower_components/fizzy-ui-utils@github:metafizzy/fizzy-ui-utils#^2.0.0 Command failed: /usr/bin/git checkout ^2.0.0
637 silly fetchPackageMetaData error: pathspec '^2.0.0' did not match any file(s) known to git.
638 silly fetchPackageMetaData error for @bower_components/get-size@github:desandro/get-size#^2.0.2 Command failed: /usr/bin/git checkout ^2.0.2
638 silly fetchPackageMetaData error: pathspec '^2.0.2' did not match any file(s) known to git.
639 silly fetchPackageMetaData error for @bower_components/fitvids@github:davatron5000/FitVids.js#~1.2.0 Command failed: /usr/bin/git checkout ~1.2.0
639 silly fetchPackageMetaData error: pathspec '~1.2.0' did not match any file(s) known to git.
640 silly fetchPackageMetaData error for @bower_components/imagesloaded@github:desandro/imagesloaded#~4.1.1 Command failed: /usr/bin/git checkout ~4.1.1
640 silly fetchPackageMetaData error: pathspec '~4.1.1' did not match any file(s) known to git.
641 silly fetchPackageMetaData error for @bower_components/highlightjs@github:components/highlightjs#~9.10.0 Command failed: /usr/bin/git checkout ~9.10.0
641 silly fetchPackageMetaData error: pathspec '~9.10.0' did not match any file(s) known to git.
642 silly fetchPackageMetaData error for @bower_components/masonry@github:desandro/masonry#~4.1.1 Command failed: /usr/bin/git checkout ~4.1.1
642 silly fetchPackageMetaData error: pathspec '~4.1.1' did not match any file(s) known to git.
643 silly fetchPackageMetaData error for @bower_components/outlayer@github:metafizzy/outlayer#^2.1.0 Command failed: /usr/bin/git checkout ^2.1.0
643 silly fetchPackageMetaData error: pathspec '^2.1.0' did not match any file(s) known to git.
644 silly fetchPackageMetaData error for @bower_components/nprogress@github:rstacruz/nprogress#~0.2.0 Command failed: /usr/bin/git checkout ~0.2.0
644 silly fetchPackageMetaData error: pathspec '~0.2.0' did not match any file(s) known to git.
645 silly fetchPackageMetaData error for @bower_components/history.js@github:browserstate/history.js#~1.8.0 Command failed: /usr/bin/git checkout ~1.8.0
645 silly fetchPackageMetaData error: pathspec '~1.8.0' did not match any file(s) known to git.
646 silly fetchPackageMetaData error for @bower_components/jquery@github:jquery/jquery-dist#~2.2.4 Command failed: /usr/bin/git checkout ~2.2.4
646 silly fetchPackageMetaData error: pathspec '~2.2.4' did not match any file(s) known to git.
647 silly fetchPackageMetaData error for @bower_components/normalize.css@github:necolas/normalize.css#~5.0.0 Command failed: /usr/bin/git checkout ~5.0.0
647 silly fetchPackageMetaData error: pathspec '~5.0.0' did not match any file(s) known to git.
648 timing stage:rollbackFailedOptional Completed in 0ms
649 timing stage:runTopLevelLifecycles Completed in 8310ms
650 silly saveTree hugo-theme-bleak@1.0.6
650 silly saveTree └─┬ grunt-cli@1.2.0
650 silly saveTree   ├─┬ findup-sync@0.3.0
650 silly saveTree   │ └─┬ glob@5.0.15
650 silly saveTree   │   ├─┬ inflight@1.0.6
650 silly saveTree   │   │ ├─┬ once@1.4.0
650 silly saveTree   │   │ │ └── wrappy@1.0.2
650 silly saveTree   │   │ └── wrappy@1.0.2
650 silly saveTree   │   ├── inherits@2.0.3
650 silly saveTree   │   ├─┬ minimatch@3.0.4
650 silly saveTree   │   │ └─┬ brace-expansion@1.1.11
650 silly saveTree   │   │   ├── balanced-match@1.0.0
650 silly saveTree   │   │   └── concat-map@0.0.1
650 silly saveTree   │   ├── once@1.4.0
650 silly saveTree   │   └── path-is-absolute@1.0.1
650 silly saveTree   ├── grunt-known-options@1.1.0
650 silly saveTree   ├─┬ nopt@3.0.6
650 silly saveTree   │ └── abbrev@1.1.1
650 silly saveTree   └── resolve@1.1.7
651 verbose stack Error: Command failed: /usr/bin/git checkout ^1.0.0
651 verbose stack error: pathspec '^1.0.0' did not match any file(s) known to git.
651 verbose stack
651 verbose stack     at ChildProcess.exithandler (child_process.js:282:12)
651 verbose stack     at ChildProcess.emit (events.js:182:13)
651 verbose stack     at maybeClose (internal/child_process.js:957:16)
651 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)
652 verbose cwd /home/arch/hackallthethings/werunskenntderkenntuns.de/themes/hugo-theme-bleak
653 verbose Linux 4.16.9-1-ARCH
654 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
655 verbose node v10.1.0
656 verbose npm  v6.0.1
657 error code 1
658 error Command failed: /usr/bin/git checkout ^1.0.0
658 error error: pathspec '^1.0.0' did not match any file(s) known to git.
659 verbose exit [ 1, true ]
```

Any idea how I can recompile the theme?

**Comment by Christian-Oette** [comment]
Have you found a solution yet? I have the same issue.

**Comment by Christian-Oette** [comment]
Try updating the dependencies in package.json (see https://www.npmjs.com)
e.g.

  "devDependencies": {
    "autoprefixer": "^6.5.4",
    "grunt": "^1.0.1",
    "grunt-contrib-clean": "^2.0.0",
    "grunt-contrib-copy": "^1.0.0",
    "grunt-contrib-cssmin": "^1.0.2",
    "grunt-contrib-uglify": "^2.0.0",
    "grunt-contrib-watch": "^1.1.0",
    "grunt-postcss": "^0.8.0",
    "grunt-sass": "^3.0.2",
    "load-grunt-tasks": "^3.5.2"
...
"engines": {
    "yarn": ">= 1.12.0"
  },

and use yarn instead of npm
